---
apiVersion: v1
kind: Namespace
metadata:
  name: "tunnel"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tunnel-server-conf
  namespace: tunnel
data:
  start.sh: |
      export AUTOSSH_LOGFILE="$HOME/autossh.log"
      export AUTOSSH_LOGLEVEL=7
      export AUTOSSH_DEBUG
     
      autossh -f -M 0 \
        -o "ServerAliveInterval 30" \
        -o "ServerAliveCountMax 3" \
        -N \
        -R 1080:localhost:1080 \
        -R 8888:localhost:8888 \
        -R 2222:localhost:22 \
        -p 22 \
        -i /tmp/ssh/id_rsa \
        -o "StrictHostKeyChecking=no" \
        mac@macos.worldl.xpt \
    
       tail -f   "$HOME/autossh.log"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tunnel-server
  namespace: tunnel
  labels:
    app.kubernetes.io/name: tunnel-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tunnel-server
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tunnel-server
    spec:
      volumes:
        - name: tunnel-conf
          configMap:
            name: tunnel-server-conf
            items:
              - key: start.sh
                path: start.sh
        - name: ssh
          secret:
            secretName: ssh
            optional: false
            defaultMode: 0700
      containers:
        - name: tunnel-server-gateway
          image: docker-command:latest
          imagePullPolicy: Never
          #command: ["/bin/sh", "-c", "sleep 10000"]
          volumeMounts:
            - name: tunnel-conf
              readOnly: true
              mountPath: /tmp/conf
            # kubectl create -n tunnel secret generic ssh --from-file=id_rsa=~/.ssh/id_rsa_tunnel
            - name: ssh
              readOnly: true
              mountPath: "/tmp/ssh"
